name = "apRQA"
uuid = "8d7a86c0-9208-4ca2-a270-64188500dc33"
version = "1.4"
authors = ["Norbert Marwan <marwan@pik-potsdam.de>"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
RecurrenceAnalysis = "639c3291-70d9-5ea2-8c5b-839eba1ee399"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DelimitedFiles = "1.9.1"
DynamicalSystems = "3.0.0"
RecurrenceAnalysis = "2.0.8"
Revise = "3.12.2"
StatsBase = "0.34.8"
