name = "aRQA"
uuid = "8d7a86c0-9208-4ca2-a270-64188500dc33"
version = "0.1.0"
authors = ["Norbert Marwan <marwan@pik-potsdam.de>"]

[deps]
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecurrenceAnalysis = "639c3291-70d9-5ea2-8c5b-839eba1ee399"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DynamicalSystems = "3.0.0"
LinearAlgebra = "1.12.0"
RecurrenceAnalysis = "2.0.8"
StatsBase = "0.34.8"
